server:
  port: 8080

spring:
  application:
    name: user

---

spring:
  config:
    activate:
      on-profile: default
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function:
      definition: updateBookRead;authorApproved
    stream:
      default:
        contentType: application/json
      bindings:
        updateBookRead-in-0:
          destination: aivlecloudnative
          group: user-update-book
          contentType: application/json

        authorApproved-in-0:
          destination: aivlecloudnative
          group: user-author-approved
          contentType: application/json

        event-out:
          destination: aivlecloudnative
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde

logging:
  level:
    org.hibernate: info
    org.springframework.cloud: debug
    aivlecloudnative.infra.OutboxPublisher: warn

server:
  port: 8082

# TODO: docker profile에도 추가
jwt:
  secret: ${JWT_SECRET}
---

spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function:
      definition: updateBookRead;authorApproved
    stream:
      default:
        contentType: application/json
      bindings:
        updateBookRead-in-0:
          destination: aivlecloudnative
          group: user-update-book
          contentType: application/json

        authorApproved-in-0:
          destination: aivlecloudnative
          group: user-author-approved
          contentType: application/json

        event-out:
          destination: aivlecloudnative
          contentType: application/json
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde

