server:
  port: 8080

spring:
  application:
    name: user

---

spring:
  config:
    activate:
      on-profile: default  # ✅ 고쳐야 할 부분
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      bindings:
        event-in:
          destination: aivlecloudnative
          group: user
          contentType: application/json
        event-out:
          destination: aivlecloudnative
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: docker  # ✅ 고쳐야 할 부분
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      bindings:
        event-in:
          destination: aivlecloudnative
          group: user
          contentType: application/json
        event-out:
          destination: aivlecloudnative
          contentType: application/json
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
