server:
    port: 8080

spring:
    application:
        name: point

---

spring:
    config:
      activate:
        on-profile: default
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: 
        driver-class-name: org.h2.Driver
    jpa:
        properties:
            hibernate:
            show_sql: true
            format_sql: true
            implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
                    autoAddPartitions: true
                    autoCreateTopics: true
                    consumer-properties:
                        value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                        spring.json.value.default.type: aivlecloudnative.domain.PointsDeducted
                        spring.json.trusted.packages: "*"
                        spring.json.use.type.headers: true
                    streams:
                        binder:
                            configuration:
                            default:
                                key:
                                    serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                                value:
                                    serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            function:
                definition: processSubscriberSignedUp;processAccessRequestedWithPoints;processPointsGrantedEvent;processPointsDeductedEvent                
            bindings:
                processSubscriberSignedUp-in-0:
                    destination: aivlecloudnative
                    group: point
                    contentType: application/json
                processAccessRequestedWithPoints-in-0:
                    destination: access_requested_with_points
                    group: point
                    contentType: application/json

                processPointsGrantedEvent-in-0:
                    destination: points_granted
                    group: point
                    contentType: application/json
                processPointsDeductedEvent-in-0:
                    destination: points_deducted
                    group: point-v2
                    contentType: application/json

                pointsGranted-out-0:
                    destination: points_granted
                    contentType: application/json
                pointsDeducted-out-0:
                    destination: points_deducted
                    contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
    org.springframework.kafka.listener: debug
    org.springframework.messaging: debug

---

server:
  port: 8087

spring:
    config:
        activate:
            on-profile: docker
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    cloud:
        stream:
            kafka:
                binder:
                    brokers: my-kafka:9092
                    autoAddPartitions: true
                    autoCreateTopics: true
                    consumer-properties:
                        value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                        spring.json.value.default.type: aivlecloudnative.domain.PointsDeducted
                        spring.json.trusted.packages: "*"
                        spring.json.use.type.headers: true
            streams:
                binder:
                    configuration:
                        default:
                            key:
                                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                            value:
                                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        function:
            definition: processSubscriberSignedUp;processAccessRequestedWithPoints;processPointsGrantedEvent;processPointsDeductedEvent
        bindings:
            processSubscriberSignedUp-in-0:
                destination: aivlecloudnative
                group: point
                contentType: application/json
            processAccessRequestedWithPoints-in-0:
                destination: access_requested_with_points
                group: point
                contentType: application/json

            processPointsGrantedEvent-in-0:
                destination: points_granted
                group: point
                contentType: application/json
            processPointsDeductedEvent-in-0:
                destination: points_deducted
                group: point-v2
                contentType: application/json

            pointsGranted-out-0:
                destination: points_granted
                contentType: application/json
            pointsDeducted-out-0:
                destination: points_deducted
                contentType: application/json




      
          
