server:
  port: 8080

spring:
  application:
    name: writing
  # --- 기본 프로필 (default) 설정 ---
  config:
    activate:
      on-profile: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: writing
          destination: aivlecloudnative #<<< EDA / Topic Name
          contentType: application/json
        event-out:
          destination: aivlecloudnative #<<< EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


--- # --- 여기는 프로필 간의 구분선입니다. ---

server:
  port: 8086 # Docker

spring:
  # --- Docker 프로필 설정 ---
  config:
    activate:
      on-profile: docker # 'spring.profiles: docker'를 이처럼 변경합니다.
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: writing
          destination: aivlecloudnative
          contentType: application/json
        event-out:
          destination: aivlecloudnative
          contentType: application/json